name: edp
version: 1.0.0
config-version: 2

profile: edp

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

clean-targets:
  - target
  - dbt_packages

models:
  edp:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: view
      +schema: int
    marts:
      +materialized: view
      +schema: mart
