from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from models.common import metadata


metadata_obj = metadata()

source_system = sa.Table(
    "source_system",
    metadata_obj,
    sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True),
    sa.Column("code", sa.Text(), nullable=False),
    sa.Column("name", sa.Text(), nullable=False),
    sa.Column("category", sa.Text(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.UniqueConstraint("code", name="uq_source_system_code"),
    schema="meta",
)

ingestion_run = sa.Table(
    "ingestion_run",
    metadata_obj,
    sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True),
    sa.Column("source_system_id", sa.BigInteger(), nullable=False),
    sa.Column("run_key", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("record_count", sa.BigInteger(), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(
        ["source_system_id"],
        ["meta.source_system.id"],
        name="fk_ingestion_run_source_system",
    ),
    sa.UniqueConstraint("run_key", name="uq_ingestion_run_run_key"),
    schema="meta",
)

ad_object_record = sa.Table(
    "object_record",
    metadata_obj,
    sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True),
    sa.Column("source_system_id", sa.BigInteger(), nullable=False),
    sa.Column("ingestion_run_id", sa.BigInteger(), nullable=False),
    sa.Column("source_object_key", sa.Text(), nullable=False),
    sa.Column("object_class", sa.Text(), nullable=False),
    sa.Column("distinguished_name", sa.Text(), nullable=True),
    sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(
        ["source_system_id"],
        ["meta.source_system.id"],
        name="fk_ad_object_record_source_system",
    ),
    sa.ForeignKeyConstraint(
        ["ingestion_run_id"],
        ["meta.ingestion_run.id"],
        name="fk_ad_object_record_ingestion_run",
    ),
    sa.UniqueConstraint(
        "source_system_id",
        "source_object_key",
        "extracted_at",
        name="uq_ad_object_record_natural_load",
    ),
    sa.Index("ix_ad_object_record_payload_gin", "payload", postgresql_using="gin"),
    schema="ad",
)

ad_sync_runs = sa.Table(
    "sync_runs",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("rows_read", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column("rows_written", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Index("ix_ad_sync_runs_source_key", "source_key"),
    sa.Index("ix_ad_sync_runs_status", "status"),
    schema="ad",
)

ad_sync_state = sa.Table(
    "sync_state",
    metadata_obj,
    sa.Column("source_key", sa.Text(), primary_key=True),
    sa.Column("entity", sa.Text(), primary_key=True),
    sa.Column("last_cursor", sa.DateTime(timezone=True), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    schema="ad",
)

ad_users = sa.Table(
    "users",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("object_guid", sa.Text(), nullable=False),
    sa.Column("distinguished_name", sa.Text(), nullable=True),
    sa.Column("sam_account_name", sa.Text(), nullable=True),
    sa.Column("user_principal_name", sa.Text(), nullable=True),
    sa.Column("display_name", sa.Text(), nullable=True),
    sa.Column("email", sa.Text(), nullable=True),
    sa.Column("enabled", sa.Text(), nullable=True),
    sa.Column("when_changed", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(
        ["sync_run_id"],
        ["ad.sync_runs.id"],
        name="fk_ad_users_sync_run_id",
        ondelete="SET NULL",
    ),
    sa.Index("ix_ad_users_object_guid", "object_guid"),
    sa.Index("ix_ad_users_sam_account_name", "sam_account_name"),
    sa.Index("ix_ad_users_user_principal_name", "user_principal_name"),
    sa.Index("ix_ad_users_sync_run_id", "sync_run_id"),
    sa.Index("ix_ad_users_when_changed", "when_changed"),
    schema="ad",
)

ad_groups = sa.Table(
    "groups",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("object_guid", sa.Text(), nullable=False),
    sa.Column("distinguished_name", sa.Text(), nullable=True),
    sa.Column("sam_account_name", sa.Text(), nullable=True),
    sa.Column("name", sa.Text(), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("when_changed", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(
        ["sync_run_id"],
        ["ad.sync_runs.id"],
        name="fk_ad_groups_sync_run_id",
        ondelete="SET NULL",
    ),
    sa.Index("ix_ad_groups_object_guid", "object_guid"),
    sa.Index("ix_ad_groups_sam_account_name", "sam_account_name"),
    sa.Index("ix_ad_groups_sync_run_id", "sync_run_id"),
    sa.Index("ix_ad_groups_when_changed", "when_changed"),
    schema="ad",
)

ad_group_memberships = sa.Table(
    "group_memberships",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("group_guid", sa.Text(), nullable=False),
    sa.Column("member_guid", sa.Text(), nullable=False),
    sa.Column("member_type", sa.Text(), nullable=False),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(
        ["sync_run_id"],
        ["ad.sync_runs.id"],
        name="fk_ad_group_memberships_sync_run_id",
        ondelete="SET NULL",
    ),
    sa.Index("ix_ad_group_memberships_group_guid", "group_guid"),
    sa.Index("ix_ad_group_memberships_member_guid", "member_guid"),
    sa.Index("ix_ad_group_memberships_sync_run_id", "sync_run_id"),
    schema="ad",
)

ad_computers = sa.Table(
    "computers",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("object_guid", sa.Text(), nullable=False),
    sa.Column("distinguished_name", sa.Text(), nullable=True),
    sa.Column("sam_account_name", sa.Text(), nullable=True),
    sa.Column("dns_host_name", sa.Text(), nullable=True),
    sa.Column("operating_system", sa.Text(), nullable=True),
    sa.Column("when_changed", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(
        ["sync_run_id"],
        ["ad.sync_runs.id"],
        name="fk_ad_computers_sync_run_id",
        ondelete="SET NULL",
    ),
    sa.Index("ix_ad_computers_object_guid", "object_guid"),
    sa.Index("ix_ad_computers_sam_account_name", "sam_account_name"),
    sa.Index("ix_ad_computers_sync_run_id", "sync_run_id"),
    sa.Index("ix_ad_computers_when_changed", "when_changed"),
    schema="ad",
)

m365_sync_runs = sa.Table(
    "sync_runs",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("rows_read", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column("rows_written", sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Index("ix_m365_sync_runs_source_key", "source_key"),
    sa.Index("ix_m365_sync_runs_status", "status"),
    schema="m365",
)

m365_users = sa.Table(
    "users",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("source_object_id", sa.Text(), nullable=True),
    sa.Column("user_principal_name", sa.Text(), nullable=True),
    sa.Column("display_name", sa.Text(), nullable=True),
    sa.Column("email", sa.Text(), nullable=True),
    sa.Column("enabled", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_users_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_users_source_object_id", "source_object_id"),
    sa.Index("ix_m365_users_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_groups = sa.Table(
    "groups",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("source_object_id", sa.Text(), nullable=True),
    sa.Column("display_name", sa.Text(), nullable=True),
    sa.Column("mail_enabled", sa.Text(), nullable=True),
    sa.Column("security_enabled", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_groups_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_groups_source_object_id", "source_object_id"),
    sa.Index("ix_m365_groups_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_group_memberships = sa.Table(
    "group_memberships",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("group_object_id", sa.Text(), nullable=True),
    sa.Column("member_object_id", sa.Text(), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_group_memberships_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_group_memberships_group_object_id", "group_object_id"),
    sa.Index("ix_m365_group_memberships_member_object_id", "member_object_id"),
    sa.Index("ix_m365_group_memberships_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_teams = sa.Table(
    "teams",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("team_id", sa.Text(), nullable=False),
    sa.Column("display_name", sa.Text(), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("visibility", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_teams_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_teams_team_id", "team_id"),
    sa.Index("ix_m365_teams_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_channels = sa.Table(
    "channels",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("team_id", sa.Text(), nullable=False),
    sa.Column("channel_id", sa.Text(), nullable=False),
    sa.Column("display_name", sa.Text(), nullable=True),
    sa.Column("membership_type", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_channels_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_channels_team_channel", "team_id", "channel_id"),
    sa.Index("ix_m365_channels_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_team_memberships = sa.Table(
    "team_memberships",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("team_id", sa.Text(), nullable=False),
    sa.Column("member_object_id", sa.Text(), nullable=False),
    sa.Column("member_ref_id", sa.Text(), nullable=True),
    sa.Column("roles", sa.Text(), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_team_memberships_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_team_memberships_team_member", "team_id", "member_object_id"),
    sa.Index("ix_m365_team_memberships_sync_run_id", "sync_run_id"),
    schema="m365",
)

m365_channel_memberships = sa.Table(
    "channel_memberships",
    metadata_obj,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("snapshot_mode", sa.Text(), nullable=False),
    sa.Column("snapshot_ts", sa.DateTime(timezone=True), nullable=False),
    sa.Column("team_id", sa.Text(), nullable=False),
    sa.Column("channel_id", sa.Text(), nullable=False),
    sa.Column("member_object_id", sa.Text(), nullable=False),
    sa.Column("member_ref_id", sa.Text(), nullable=True),
    sa.Column("roles", sa.Text(), nullable=True),
    sa.Column("sync_run_id", sa.Text(), nullable=True),
    sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(["sync_run_id"], ["m365.sync_runs.id"], name="fk_m365_channel_memberships_sync_run_id", ondelete="SET NULL"),
    sa.Index("ix_m365_channel_memberships_channel_member", "team_id", "channel_id", "member_object_id"),
    sa.Index("ix_m365_channel_memberships_sync_run_id", "sync_run_id"),
    schema="m365",
)
