param(
    [string]$SourceRoot = (Join-Path $PSScriptRoot "..\contrib\sources"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\contrib\INDEX.md"),
    [int]$LargestFileCount = 20,
    [long]$NormalGitBlobLimitBytes = 100MB
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$workspaceRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$resolvedSourceRoot = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($SourceRoot)
$resolvedOutputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)

if (-not $resolvedSourceRoot.StartsWith($workspaceRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "SourceRoot must stay inside the workspace: $workspaceRoot"
}

if (-not $resolvedOutputPath.StartsWith($workspaceRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputPath must stay inside the workspace: $workspaceRoot"
}

if (-not (Test-Path -LiteralPath $resolvedSourceRoot)) {
    throw "Contrib source root does not exist: $resolvedSourceRoot"
}

function Format-FileSize {
    param([long]$Bytes)

    if ($Bytes -ge 1GB) {
        return "{0:N2} GB" -f ($Bytes / 1GB)
    }

    if ($Bytes -ge 1MB) {
        return "{0:N2} MB" -f ($Bytes / 1MB)
    }

    if ($Bytes -ge 1KB) {
        return "{0:N2} KB" -f ($Bytes / 1KB)
    }

    return "$Bytes B"
}

function Get-RelativePath {
    param(
        [string]$BasePath,
        [string]$Path
    )

    $baseUri = [System.Uri]::new(($BasePath.TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar))
    $pathUri = [System.Uri]::new($Path)
    return [System.Uri]::UnescapeDataString($baseUri.MakeRelativeUri($pathUri).ToString()).Replace("/", [System.IO.Path]::DirectorySeparatorChar)
}

function Get-FileLengthSum {
    param([object[]]$Files)

    if ($Files.Count -eq 0) {
        return 0
    }

    $measure = $Files | Measure-Object -Property Length -Sum
    if ($null -eq $measure -or $null -eq $measure.Sum) {
        return 0
    }

    return [long]$measure.Sum
}

$providerNames = @{
    "cis" = "Center for Internet Security"
    "cisa" = "Cybersecurity and Infrastructure Security Agency"
    "ieee" = "IEEE SA"
    "nist" = "National Institute of Standards and Technology"
    "policy-templates" = "Policy Templates"
    "purple-knight" = "Purple Knight"
}

$providerDirectories = Get-ChildItem -LiteralPath $resolvedSourceRoot -Directory | Sort-Object Name
$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("# Contrib Source Index")
$lines.Add("")
$lines.Add("Generated by ``scripts/Update-ContribIndex.ps1`` on $generatedAt.")
$lines.Add("")
$lines.Add("This index summarizes the restored source tree under ``contrib/sources``. Source documents are part of the contrib workspace; derived requirements should still be captured in first-class EDP docs, models, migrations, dbt assets, or tests.")
$lines.Add("")
$lines.Add("Files larger than GitHub's normal 100 MB blob limit are listed here for local inventory but are excluded from Git by ``contrib/.gitignore`` unless the repository adopts a large-artifact store.")
$lines.Add("")
$lines.Add("## Provider Summary")
$lines.Add("")
$lines.Add("| Provider | Folder | Files | Size | Primary Extensions |")
$lines.Add("| --- | --- | ---: | ---: | --- |")

$allFiles = @()
$providerDetails = @()

foreach ($directory in $providerDirectories) {
    $files = @(Get-ChildItem -LiteralPath $directory.FullName -File -Recurse -Force)
    $allFiles += $files
    $totalBytes = Get-FileLengthSum -Files $files

    $extensions = $files |
        Group-Object { if ([string]::IsNullOrWhiteSpace($_.Extension)) { "[none]" } else { $_.Extension.ToLowerInvariant() } } |
        Sort-Object -Property @{ Expression = "Count"; Descending = $true }, @{ Expression = "Name"; Descending = $false } |
        Select-Object -First 6 |
        ForEach-Object { "$($_.Name) ($($_.Count))" }

    $displayName = $providerNames[$directory.Name]
    if ([string]::IsNullOrWhiteSpace($displayName)) {
        $displayName = $directory.Name
    }

    $relativeFolder = Get-RelativePath -BasePath $workspaceRoot -Path $directory.FullName
    $lines.Add("| $displayName | ``$relativeFolder`` | $($files.Count) | $(Format-FileSize -Bytes ([long]$totalBytes)) | $($extensions -join ", ") |")

    $providerDetails += [pscustomobject]@{
        Name = $displayName
        Directory = $directory
        Files = $files
        TotalBytes = [long]$totalBytes
    }
}

$totalSize = Get-FileLengthSum -Files $allFiles

$lines.Add("")
$lines.Add("Total files: $($allFiles.Count)")
$lines.Add("")
$lines.Add("Total size: $(Format-FileSize -Bytes ([long]$totalSize))")
$lines.Add("")
$lines.Add("## Largest Files")
$lines.Add("")
$lines.Add("| Size | Path |")
$lines.Add("| ---: | --- |")

$allFiles |
    Sort-Object Length -Descending |
    Select-Object -First $LargestFileCount |
    ForEach-Object {
        $relativePath = Get-RelativePath -BasePath $workspaceRoot -Path $_.FullName
        $lines.Add("| $(Format-FileSize -Bytes $_.Length) | ``$relativePath`` |")
    }

$oversizedFiles = @($allFiles | Where-Object { $_.Length -gt $NormalGitBlobLimitBytes } | Sort-Object Length -Descending)
if ($oversizedFiles.Count -gt 0) {
    $lines.Add("")
    $lines.Add("## Oversized Local Files")
    $lines.Add("")
    $lines.Add("These files are intentionally kept out of normal Git because they exceed GitHub's 100 MB blob limit.")
    $lines.Add("")
    $lines.Add("| Size | Path |")
    $lines.Add("| ---: | --- |")

    $oversizedFiles |
        ForEach-Object {
            $relativePath = Get-RelativePath -BasePath $workspaceRoot -Path $_.FullName
            $lines.Add("| $(Format-FileSize -Bytes $_.Length) | ``$relativePath`` |")
        }
}

$lines.Add("")
$lines.Add("## Provider Notes")

foreach ($provider in ($providerDetails | Sort-Object Name)) {
    $lines.Add("")
    $lines.Add("### $($provider.Name)")
    $lines.Add("")
    $relativeFolder = Get-RelativePath -BasePath $workspaceRoot -Path $provider.Directory.FullName
    $lines.Add("- Folder: ``$relativeFolder``")
    $lines.Add("- Files: $($provider.Files.Count)")
    $lines.Add("- Size: $(Format-FileSize -Bytes $provider.TotalBytes)")

    $topLevel = @($provider.Files |
        ForEach-Object {
            $relativeToProvider = Get-RelativePath -BasePath $provider.Directory.FullName -Path $_.FullName
            $firstSegment = $relativeToProvider.Split([System.IO.Path]::DirectorySeparatorChar)[0]
            if ([string]::IsNullOrWhiteSpace($firstSegment)) { $_.Name } else { $firstSegment }
        } |
        Group-Object |
        Sort-Object -Property @{ Expression = "Count"; Descending = $true }, @{ Expression = "Name"; Descending = $false } |
        Select-Object -First 12 |
        ForEach-Object { "$($_.Name) ($($_.Count))" })

    if ($topLevel.Count -gt 0) {
        $lines.Add("- Top-level contents: $($topLevel -join ", ")")
    }
}

$outputDirectory = Split-Path -Parent $resolvedOutputPath
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$lines | Set-Content -LiteralPath $resolvedOutputPath -Encoding UTF8

Write-Host "Wrote contrib index to $resolvedOutputPath"
