#!/bin/sh
set -eu

cat > /tmp/pgbouncer-userlist.txt <<EOF
"${POSTGRES_USER}" "${POSTGRES_PASSWORD}"
"${AIRFLOW_DATABASE_USER}" "${AIRFLOW_DATABASE_PASSWORD}"
"${SUPERSET_DATABASE_USER}" "${SUPERSET_DATABASE_PASSWORD}"
"${OPENMETADATA_DATABASE_USER}" "${OPENMETADATA_DATABASE_PASSWORD}"
"${OPENMETADATA_AIRFLOW_DATABASE_USER}" "${OPENMETADATA_AIRFLOW_DATABASE_PASSWORD}"
"${CKAN_DATABASE_USER}" "${CKAN_DATABASE_PASSWORD}"
"${CKAN_DATASTORE_READONLY_USER}" "${CKAN_DATASTORE_READONLY_PASSWORD}"
EOF

exec pgbouncer /etc/pgbouncer/pgbouncer.ini
