[alembic]
script_location = %(here)s/migrations/raw
prepend_sys_path = %(here)s
timezone = UTC

[raw]
script_location = %(here)s/migrations/raw
prepend_sys_path = %(here)s
timezone = UTC
sqlalchemy.url = postgresql+psycopg://postgres:postgres@pgbouncer:6432/edp_raw

[ods]
script_location = %(here)s/migrations/ods
prepend_sys_path = %(here)s
timezone = UTC
sqlalchemy.url = postgresql+psycopg://postgres:postgres@pgbouncer:6432/edp_ods

[vault]
script_location = %(here)s/migrations/vault
prepend_sys_path = %(here)s
timezone = UTC
sqlalchemy.url = postgresql+psycopg://postgres:postgres@pgbouncer:6432/edp_vault

[mart]
script_location = %(here)s/migrations/mart
prepend_sys_path = %(here)s
timezone = UTC
sqlalchemy.url = postgresql+psycopg://postgres:postgres@pgbouncer:6432/edp_mart

[app]
script_location = %(here)s/migrations/app
prepend_sys_path = %(here)s
timezone = UTC
sqlalchemy.url = postgresql+psycopg://postgres:postgres@pgbouncer:6432/edp_app

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
